# Generated by Django 4.2.2 on 2023-12-03 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('text', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(11, 'Sending'), (21, 'Sent'), (31, 'Failed')], default=11)),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('receiver_id', models.CharField(max_length=64)),
                ('chat_id', models.CharField(max_length=64)),
                ('message_id', models.CharField(max_length=64, unique=True)),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', related_query_name='message', to='core.project')),
                ('sender_bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', related_query_name='message', to='core.telegrambot')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
    ]
