# Generated by Django 4.2.14 on 2024-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="enable_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="message",
            name="parse_mode",
            field=models.PositiveSmallIntegerField(choices=[(1, "Normal"), (2, "MarkdownV2"), (3, "HTML")], default=1),
        ),
    ]
